# Read Data

In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
import pandas as pd
A=pd.read_csv("C:/Users/Suja4/OneDrive/Documents/Data Science/Dataset/Cars93.csv")

In [3]:
A.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

# Remove null values

In [4]:
A.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [5]:
from Wd8pm import replacer
replacer(A)

In [6]:
A.isna().sum()

id                    0
Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

# Outlier removal

In [7]:
from Wd8pm import OL

In [8]:
outlier=OL(A)

In [9]:
outlier

[16, 38, 41, 47, 58, 59]

In [10]:
A=A.drop(index=outlier,axis=0)

In [11]:
A.shape

(87, 28)

In [12]:
A.index=range(0,87)

# Remove unique values

In [13]:
A.nunique()

id                    87
Manufacturer          31
Model                 87
Type                   6
Min.Price             75
Price                 76
Max.Price             74
MPG.city              19
MPG.highway           20
AirBags                3
DriveTrain             3
Cylinders              6
EngineSize            23
Horsepower            52
RPM                   22
Rev.per.mile          73
Man.trans.avail        2
Fuel.tank.capacity    35
Passengers             5
Length                50
Wheelbase             26
Width                 16
Turn.circle           14
Rear.seat.room        22
Luggage.room          16
Weight                76
Origin                 2
Make                  87
dtype: int64

In [14]:
X=A.drop(labels=["id","Model","Make","Origin"],axis=1)
Y=A[['Origin']]

# Bivariate Analysis

In [15]:
from Wd8pm import ANOVA,chisq

In [16]:
A = A.rename(columns = {"Min.Price":"Min_Price","Max.Price":"Max_Price","MPG.city":"MPG_city","MPG.highway":"MPG_highway"
    ,"Rev.per.mile":"Rev_per_mile","Man.trans.avail":"Man_trans_avail","Fuel.tank.capacity":"Fuel_tank_capacity",
                        "Turn.circle":"Turn_circle","Rear.seat.room":"Rear_seat_room","Luggage.room":"Luggage_room"})
X = X.rename(columns = {"Min.Price":"Min_Price","Max.Price":"Max_Price","MPG.city":"MPG_city","MPG.highway":"MPG_highway"
    ,"Rev.per.mile":"Rev_per_mile","Man.trans.avail":"Man_trans_avail","Fuel.tank.capacity":"Fuel_tank_capacity",
                        "Turn.circle":"Turn_circle","Rear.seat.room":"Rear_seat_room","Luggage.room":"Luggage_room"})

In [17]:
A.head()

,id,Manufacturer,Model,Type,Min_Price,Price,Max_Price,MPG_city,MPG_highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn_circle,Rear_seat_room,Luggage_room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver only,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [18]:
for i in X.columns:
    if(X[i].dtypes=="object"):
        pvalue=chisq(A,'Origin',i)
        print(i ,"---Chisq---", pvalue)
    else:
        pvalue=ANOVA(A,'Origin',i)
        print(i ,"--------Anova---", pvalue)

Manufacturer ---Chisq--- 0.0
Type ---Chisq--- 0.02974
Min_Price --------Anova--- 0.86094
Price --------Anova--- 0.72669
Max_Price --------Anova--- 0.63056
MPG_city --------Anova--- 0.03227
MPG_highway --------Anova--- 0.22786
AirBags ---Chisq--- 0.72301
DriveTrain ---Chisq--- 0.59675
Cylinders ---Chisq--- 0.01508
EngineSize --------Anova--- 4e-05
Horsepower --------Anova--- 0.33147
RPM --------Anova--- 0.0
Rev_per_mile --------Anova--- 1e-05
Man_trans_avail ---Chisq--- 3e-05
Fuel_tank_capacity --------Anova--- 0.28964
Passengers --------Anova--- 0.03646
Length --------Anova--- 0.00027
Wheelbase --------Anova--- 0.00435
Width --------Anova--- 2e-05
Turn_circle --------Anova--- 0.0
Rear_seat_room --------Anova--- 0.23994
Luggage_room --------Anova--- 0.00045
Weight --------Anova--- 0.04086

In [41]:
imp_cols = []
from Wd8pm import ANOVA,chisq
for i in X.columns:
    if(X[i].dtypes == "object"):
        pval = chisq(A,"Origin",i)
        print("Origin ~",i,"---->",pval)
        if(pval<0.05):
            imp_cols.append(i)
    else:
        pval = ANOVA(A,"Origin",i)
        print("Origin ~",i,"---->",pval)
        if(pval<0.05):
            imp_cols.append(i)

Origin ~ Manufacturer ----> 0.0
Origin ~ Type ----> 0.02974
Origin ~ Min_Price ----> 0.86094
Origin ~ Price ----> 0.72669
Origin ~ Max_Price ----> 0.63056
Origin ~ MPG_city ----> 0.03227
Origin ~ MPG_highway ----> 0.22786
Origin ~ AirBags ----> 0.72301
Origin ~ DriveTrain ----> 0.59675
Origin ~ Cylinders ----> 0.01508
Origin ~ EngineSize ----> 4e-05
Origin ~ Horsepower ----> 0.33147
Origin ~ RPM ----> 0.0
Origin ~ Rev_per_mile ----> 1e-05
Origin ~ Man_trans_avail ----> 3e-05
Origin ~ Fuel_tank_capacity ----> 0.28964
Origin ~ Passengers ----> 0.03646
Origin ~ Length ----> 0.00027
Origin ~ Wheelbase ----> 0.00435
Origin ~ Width ----> 2e-05
Origin ~ Turn_circle ----> 0.0
Origin ~ Rear_seat_room ----> 0.23994
Origin ~ Luggage_room ----> 0.00045
Origin ~ Weight ----> 0.04086

In [48]:
imp_cols

['Manufacturer',
 'Type',
 'MPG_city',
 'Cylinders',
 'EngineSize',
 'RPM',
 'Rev_per_mile',
 'Man_trans_avail',
 'Passengers',
 'Length',
 'Wheelbase',
 'Width',
 'Turn_circle',
 'Luggage_room',
 'Weight']

# Preprocessing

In [42]:
Ximp = X[imp_cols]

In [49]:

from Wd8pm import preprocessing
Xnew =preprocessing(Ximp)

Ximp = X[["Weight","Luggage_room","Turn_circle",'Width','Wheelbase','Length',"Passengers","Man_trans_avail","Rev_per_mile",
        "RPM","EngineSize","Cylinders", "MPG_city","Type","Manufacturer"]]

# Split

In [50]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(Xnew,Y,test_size=0.2,random_state=21)

# Model

In [51]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model=lr.fit(xtrain,ytrain)

# Prediction

In [52]:
tr_pred= model.predict(xtrain)
ts_pred=model.predict(xtest)

# Accuracy

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(ytrain,tr_pred) ,accuracy_score(ytest,ts_pred)

(0.9710144927536232, 0.9444444444444444)

In [54]:
from sklearn.metrics import confusion_matrix,recall_score
confusion_matrix(ytrain,tr_pred)

array([[31,  2],
       [ 0, 36]], dtype=int64)

In [56]:
confusion_matrix(ytest,ts_pred)

array([[12,  1],
       [ 0,  5]], dtype=int64)

# Here TP and TN are more in training data ,so it is overfitting

# Data

In [27]:
xtest['pred']=ts_pred

In [28]:
xtest.index

Int64Index([36, 47, 51, 22, 3, 24, 10, 23, 13, 40, 19, 17, 31, 57, 67, 42, 54,
            29],
           dtype='int64')

In [29]:
Xdata = Ximp.iloc[xtest.index,:]

In [30]:
Xdata['pred']=ts_pred

In [31]:
Xdata

,Weight,Luggage_room,Turn_circle,Width,Wheelbase,Length,Passengers,Man_trans_avail,Rev_per_mile,RPM,EngineSize,Cylinders,MPG_city,Type,Manufacturer,pred
36,3950,21.000000,43,78,114,212,6,No,1415,4200,4.6,8,18,Large,Ford,USA
47,4055,22.000000,45,77,117,219,6,No,1840,4600,4.6,8,18,Large,Lincoln,USA
51,3735,13.890244,39,72,110,190,7,No,2240,5000,3.0,6,18,Van,Mazda,USA
22,2670,13.000000,38,67,97,172,5,Yes,2595,4800,2.2,4,23,Small,Dodge,USA
3,3405,17.000000,37,70,106,193,6,Yes,2535,5500,2.8,6,19,Midsize,Audi,non-USA
24,3705,13.890244,42,72,112,175,7,No,1970,5000,3.0,6,17,Van,Dodge,USA
10,3935,14.000000,44,74,111,204,5,No,1985,6000,4.6,8,16,Midsize,Cadillac,non-USA
23,2970,14.000000,39,68,104,181,6,Yes,2535,4800,2.5,4,22,Compact,Dodge,USA
13,3240,13.000000,43,74,101,193,4,Yes,1805,4600,3.4,6,19,Sporty,Chevrolet,USA
40,2345,11.000000,35,63,94,168,5,Yes,2710,5500,1.5,4,29,Small,Hyundai,non-USA
19,3085,14.000000,41,68,104,183,6,No,2090,5000,3.0,4,23,Compact,Chrysler,USA
17,3380,13.890244,43,74,96,179,2,Yes,1450,5000,5.7,8,17,Sporty,Chevrolet,non-USA
31,2690,13.000000,39,68,100,177,5,Yes,2805,4200,2.3,4,22,Compact,Ford,USA
57,2545,12.000000,33,66,96,170,5,Yes,2435,6000,1.6,4,29,Small,Nissan,non-USA
67,2575,13.000000,39,66,101,181,5,Yes,2665,5200,2.0,4,23,Compact,Pontiac,USA
42,2285,9.000000,34,64,94,166,4,Yes,2540,5550,1.5,4,26,Sporty,Hyundai,non-USA
54,3610,15.000000,38,73,113,199,5,No,1730,3800,3.8,6,19,Midsize,Mercury,USA
29,1845,12.000000,33,63,90,141,4,Yes,3150,5000,1.3,4,31,Small,Ford,non-USA

In [32]:
Xdata['Y'] = Y.iloc[xtest.index]

In [33]:
Xdata

,Weight,Luggage_room,Turn_circle,Width,Wheelbase,Length,Passengers,Man_trans_avail,Rev_per_mile,RPM,EngineSize,Cylinders,MPG_city,Type,Manufacturer,pred,Y
36,3950,21.000000,43,78,114,212,6,No,1415,4200,4.6,8,18,Large,Ford,USA,USA
47,4055,22.000000,45,77,117,219,6,No,1840,4600,4.6,8,18,Large,Lincoln,USA,USA
51,3735,13.890244,39,72,110,190,7,No,2240,5000,3.0,6,18,Van,Mazda,USA,non-USA
22,2670,13.000000,38,67,97,172,5,Yes,2595,4800,2.2,4,23,Small,Dodge,USA,USA
3,3405,17.000000,37,70,106,193,6,Yes,2535,5500,2.8,6,19,Midsize,Audi,non-USA,non-USA
24,3705,13.890244,42,72,112,175,7,No,1970,5000,3.0,6,17,Van,Dodge,USA,USA
10,3935,14.000000,44,74,111,204,5,No,1985,6000,4.6,8,16,Midsize,Cadillac,non-USA,USA
23,2970,14.000000,39,68,104,181,6,Yes,2535,4800,2.5,4,22,Compact,Dodge,USA,USA
13,3240,13.000000,43,74,101,193,4,Yes,1805,4600,3.4,6,19,Sporty,Chevrolet,USA,USA
40,2345,11.000000,35,63,94,168,5,Yes,2710,5500,1.5,4,29,Small,Hyundai,non-USA,non-USA
19,3085,14.000000,41,68,104,183,6,No,2090,5000,3.0,4,23,Compact,Chrysler,USA,USA
17,3380,13.890244,43,74,96,179,2,Yes,1450,5000,5.7,8,17,Sporty,Chevrolet,non-USA,USA
31,2690,13.000000,39,68,100,177,5,Yes,2805,4200,2.3,4,22,Compact,Ford,USA,USA
57,2545,12.000000,33,66,96,170,5,Yes,2435,6000,1.6,4,29,Small,Nissan,non-USA,non-USA
67,2575,13.000000,39,66,101,181,5,Yes,2665,5200,2.0,4,23,Compact,Pontiac,USA,USA
42,2285,9.000000,34,64,94,166,4,Yes,2540,5550,1.5,4,26,Sporty,Hyundai,non-USA,non-USA
54,3610,15.000000,38,73,113,199,5,No,1730,3800,3.8,6,19,Midsize,Mercury,USA,USA
29,1845,12.000000,33,63,90,141,4,Yes,3150,5000,1.3,4,31,Small,Ford,non-USA,USA